import 'package:call_life/models/kpis_card_model.dart';
import 'package:flutter/material.dart';

List<KpisCardModel> kpisCardData = [
  KpisCardModel(
    title: 'Active Calls',
    icon: Icon(Icons.phone),
    count: '47',
    status: '+12%',
    statusColor: Colors.green,
    subtitle: 'Currently in progress',
  ),
  KpisCardModel(
    title: 'Active Calls',
    icon: Icon(Icons.phone),
    count: '47',
    status: '+12%',
    statusColor: Colors.green,
    subtitle: 'Currently in progress',
  ),
  KpisCardModel(
    title: 'Active Calls',
    icon: Icon(Icons.phone),
    count: '47',
    status: '+12%',
    statusColor: Colors.green,
    subtitle: 'Currently in progress',
  ),
  KpisCardModel(
    title: 'Active Calls',
    icon: Icon(Icons.phone),
    count: '47',
    status: '+12%',
    statusColor: Colors.green,
    subtitle: 'Currently in progress',
  ),
  KpisCardModel(
    title: 'Active Calls',
    icon: Icon(Icons.phone),
    count: '47',
    status: '+12%',
    statusColor: Colors.green,
    subtitle: 'Currently in progress',
  ),
  KpisCardModel(
    title: 'Active Calls',
    icon: Icon(Icons.phone),
    count: '47',
    status: '+12%',
    statusColor: Colors.green,
    subtitle: 'Currently in progress',
  ),
  KpisCardModel(
    title: 'Active Calls',
    icon: Icon(Icons.phone),
    count: '47',
    status: '+12%',
    statusColor: Colors.green,
    subtitle: 'Currently in progress',
  ),
  KpisCardModel(
    title: 'Active Calls',
    icon: Icon(Icons.phone),
    count: '47',
    status: '+12%',
    statusColor: Colors.green,
    subtitle: 'Currently in progress',
  ),
  KpisCardModel(
    title: 'Active Calls',
    icon: Icon(Icons.phone),
    count: '47',
    status: '+12%',
    statusColor: Colors.green,
    subtitle: 'Currently in progress',
  ),
  KpisCardModel(
    title: 'Active Calls',
    icon: Icon(Icons.phone),
    count: '47',
    status: '+12%',
    statusColor: Colors.green,
    subtitle: 'Currently in progress',
  ),
];
