import 'package:call_life/models/kpis_card_model.dart';
import 'package:flutter/material.dart';

List<KqisCardModel> kpisCardData = [
  KqisCardModel(
    title: 'Active Calls',
    icon: Icon(Icons.phone),
    count: '47',
    status: '+12%',
    statusColor: Colors.green,
    subtitle: 'Currently in progress',
  ),
  KqisCardModel(
    title: 'Active Calls',
    icon: Icon(Icons.phone),
    count: '47',
    status: '+12%',
    statusColor: Colors.green,
    subtitle: 'Currently in progress',
  ),
  KqisCardModel(
    title: 'Active Calls',
    icon: Icon(Icons.phone),
    count: '47',
    status: '+12%',
    statusColor: Colors.green,
    subtitle: 'Currently in progress',
  ),
  KqisCardModel(
    title: 'Active Calls',
    icon: Icon(Icons.phone),
    count: '47',
    status: '+12%',
    statusColor: Colors.green,
    subtitle: 'Currently in progress',
  ),
  KqisCardModel(
    title: 'Active Calls',
    icon: Icon(Icons.phone),
    count: '47',
    status: '+12%',
    statusColor: Colors.green,
    subtitle: 'Currently in progress',
  ),
  KqisCardModel(
    title: 'Active Calls',
    icon: Icon(Icons.phone),
    count: '47',
    status: '+12%',
    statusColor: Colors.green,
    subtitle: 'Currently in progress',
  ),
  // KpisCardModel(
  //   title: 'Active Calls',
  //   icon: Icon(Icons.phone),
  //   count: '47',
  //   status: '+12%',
  //   statusColor: Colors.green,
  //   subtitle: 'Currently in progress',
  // ),
  // KpisCardModel(
  //   title: 'Active Calls',
  //   icon: Icon(Icons.phone),
  //   count: '47',
  //   status: '+12%',
  //   statusColor: Colors.green,
  //   subtitle: 'Currently in progress',
  // ),
  // KpisCardModel(
  //   title: 'Active Calls',
  //   icon: Icon(Icons.phone),
  //   count: '47',
  //   status: '+12%',
  //   statusColor: Colors.green,
  //   subtitle: 'Currently in progress',
  // ),
  // KpisCardModel(
  //   title: 'Active Calls',
  //   icon: Icon(Icons.phone),
  //   count: '47',
  //   status: '+12%',
  //   statusColor: Colors.green,
  //   subtitle: 'Currently in progress',
  // ),
];
List<KqisCardModel> kqisCardData = [
  KqisCardModel(
    title: 'ASA (Average Speed of Answer)',
    icon: Icon(Icons.watch_later_outlined),
    count: '12.3s',
    status: ' -8%',
    statusColor: Colors.green,
    subtitle: 'vs last month\nAverage time to answer',
  ),
  KqisCardModel(
    title: 'FCR (First Call Resolution)',
    icon: Icon(Icons.data_saver_off_rounded),
    count: '78.4%',
    status: '+5%',
    statusColor: Colors.green,
    subtitle: 'vs last month\nResolved on first contact',
  ),
  KqisCardModel(
    title: 'AHT (Average Handling Time)',
    icon: Icon(Icons.watch_later_outlined),
    count: '4m 32s',
    status: '+2%',
    statusColor: Colors.brown,
    subtitle: 'vs last month\nAverage call duration',
  ),
];
